#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import socket
import subprocess
import platform
import threading
import json
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from datetime import datetime
import paramiko

# ========== Banner ==========
BANNER = """
███╗   ██╗███████╗██████╗ ███████╗███████╗███████╗ ██████╗ ██╗   ██╗
████╗  ██║██╔════╝██╔══██╗██╔════╝██╔════╝██╔════╝██╔═══██╗██║   ██║
██╔██╗ ██║█████╗  ██████╔╝█████╗  █████╗  ███████╗██║   ██║██║   ██║
██║╚██╗██║██╔══╝  ██╔══██╗██╔══╝  ██╔══╝  ╚════██║██║   ██║██║   ██║
██║ ╚████║███████╗██║  ██║███████╗███████╗███████║╚██████╔╝╚██████╔╝
╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝ ╚═════╝  ╚═════╝ 
             🇸🇦  snap: ml-ftt — OpenWrt Network Monitor & Disconnect
===============================================================================

"""
print(BANNER)

# ========== Config ==========
OUI_FILE = "oui.txt"  # optional vendor file
DEFAULT_HOSTS = 254

# ========== Helper Functions ==========

def get_local_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
    except Exception:
        ip = "127.0.0.1"
    finally:
        s.close()
    return ip

def network_prefix(ip):
    parts = ip.split(".")
    return ".".join(parts[:3])

def ping(ip):
    try:
        if platform.system() == "Windows":
            subprocess.check_output(["ping", "-n", "1", "-w", "700", ip],
                                    stderr=subprocess.DEVNULL)
        else:
            subprocess.check_output(["ping", "-c", "1", "-W", "1", ip],
                                    stderr=subprocess.DEVNULL)
        return True
    except Exception:
        return False

def read_arp():
    out = subprocess.getoutput("arp -a")
    lines = out.splitlines()
    result = {}
    for l in lines:
        parts = l.split()
        if len(parts) >= 3 and "." in parts[0]:
            ip = parts[0]
            mac = parts[1].replace("-", ":")
            result[ip] = mac.lower()
    return result

def get_hostname(ip):
    try:
        return socket.gethostbyaddr(ip)[0]
    except Exception:
        return ""

def load_oui(path=OUI_FILE):
    if not os.path.exists(path):
        return {}
    mapping = {}
    with open(path, encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                prefix, vendor = parts
                mapping[prefix.lower()] = vendor
    return mapping

def vendor_from_mac(mac, oui_map):
    if not mac:
        return "Unknown"
    prefix = mac.replace(":", "").replace("-", "").lower()[:6]
    return oui_map.get(prefix, "Unknown")

# ========== Script builder ==========

def build_openwrt_block_script(devices):
    """
    devices: list of dicts with keys: ip, mac, hostname, vendor, first_seen, last_seen
    returns script text as string.
    """
    lines = [
        "#!/bin/sh",
        "# Generated by Network Monitor — ViRuS-HaCkEr (ml-ftt)",
        "uci export firewall > /tmp/fw-backup.conf",
        ""
    ]
    for d in devices:
        mac = d.get("mac", "")
        if not mac:
            continue
        label = mac.replace(":", "")
        lines += [
            "uci add firewall rule",
            f"uci set firewall.@rule[-1].name='block_{label}'",
            "uci set firewall.@rule[-1].src='*'",
            "uci set firewall.@rule[-1].target='REJECT'",
            f"uci set firewall.@rule[-1].mac='{mac}'",
            "uci set firewall.@rule[-1].enabled='1'",
            ""
        ]
    lines += [
        "uci commit firewall",
        "/etc/init.d/firewall restart"
    ]
    # also iptables snippet (non-persistent)
    lines += [
        "",
        "# Optional immediate iptables drop (non-persistent):"
    ]
    for d in devices:
        mac = d.get("mac", "")
        if mac:
            lines.append(f"iptables -I FORWARD -m mac --mac-source {mac} -j DROP")
    return "\n".join(lines)

# ========== GUI App ==========

class NetworkGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Network Monitor — OpenWrt Helper (snap: ml-ftt 🇸🇦)")
        self.devices = {}  # key = IP, value = dict with info
        self.scanning = False
        self.last_script = None
        self.oui_map = load_oui()

        self.build_ui()
        # periodic refresh of tree
        self.root.after(1000, self.refresh_tree_periodic)

    # ---------- UI build ----------
    def build_ui(self):
        banner = tk.Label(
            self.root,
            text="🇸🇦  Network Monitor — OpenWrt Helper (snap: ml-ftt)",
            bg="#063306",
            fg="white",
            font=("Segoe UI Black", 16, "bold")
        )
        banner.pack(fill=tk.X, pady=6)

        sub = tk.Label(
            self.root,
            text="Monitor connected devices, generate OpenWrt firewall rules, and disconnect selected devices via SSH.",
            bg="#063306",
            fg="#c8e6c9",
            font=("Segoe UI", 9)
        )
        sub.pack(fill=tk.X)

        ctrl = tk.Frame(self.root)
        ctrl.pack(pady=4)

        local_ip = get_local_ip()
        tk.Label(ctrl, text=f"Local IP: {local_ip}").pack(side=tk.LEFT, padx=4)

        tk.Label(ctrl, text="Network Prefix:").pack(side=tk.LEFT)
        self.prefix = tk.StringVar(value=network_prefix(local_ip))
        tk.Entry(ctrl, textvariable=self.prefix, width=12).pack(side=tk.LEFT)

        tk.Label(ctrl, text="Hosts:").pack(side=tk.LEFT)
        self.range_var = tk.IntVar(value=DEFAULT_HOSTS)
        tk.Entry(ctrl, textvariable=self.range_var, width=5).pack(side=tk.LEFT)

        ttk.Button(ctrl, text="Start Scan", command=self.start_scan).pack(side=tk.LEFT, padx=5)
        ttk.Button(ctrl, text="Stop", command=self.stop_scan).pack(side=tk.LEFT)
        ttk.Button(ctrl, text="Export JSON", command=self.export_json).pack(side=tk.LEFT, padx=5)
        ttk.Button(ctrl, text="Generate Script (all)", command=self.make_script_all).pack(side=tk.LEFT, padx=5)

        # SSH / Disconnect frame
        ssh_frame = tk.LabelFrame(self.root, text="SSH & Disconnect", padx=4, pady=4)
        ssh_frame.pack(fill=tk.X, padx=10, pady=4)

        tk.Label(ssh_frame, text="Router IP:").grid(row=0, column=0, sticky="w")
        self.router_ip = tk.StringVar(value="192.168.1.1")
        tk.Entry(ssh_frame, textvariable=self.router_ip, width=14).grid(row=0, column=1)

        tk.Label(ssh_frame, text="User:").grid(row=0, column=2, sticky="w")
        self.router_user = tk.StringVar(value="root")
        tk.Entry(ssh_frame, textvariable=self.router_user, width=10).grid(row=0, column=3)

        tk.Label(ssh_frame, text="Password:").grid(row=0, column=4, sticky="w")
        self.router_pass = tk.StringVar()
        tk.Entry(ssh_frame, textvariable=self.router_pass, width=14, show="*").grid(row=0, column=5)

        ttk.Button(
            ssh_frame,
            text="Run Last Script On Router",
            command=self.deploy_last_script
        ).grid(row=0, column=6, padx=6)

        ttk.Button(
            ssh_frame,
            text="Disconnect Selected (Safe)",
            command=self.disconnect_selected
        ).grid(row=0, column=7, padx=6)

        # Tree
        cols = ("ip", "mac", "hostname", "vendor", "first_seen", "last_seen")
        self.tree = ttk.Treeview(self.root, columns=cols, show="headings")
        self.tree.heading("ip", text="IP")
        self.tree.heading("mac", text="MAC")
        self.tree.heading("hostname", text="Hostname")
        self.tree.heading("vendor", text="Vendor")
        self.tree.heading("first_seen", text="First Seen")
        self.tree.heading("last_seen", text="Last Seen")
        for c in cols:
            self.tree.column(c, width=150)
        self.tree.pack(fill=tk.BOTH, expand=True, padx=10, pady=8)

        self.status = tk.StringVar(value="Ready")
        tk.Label(self.root, textvariable=self.status, bg="#0b3a0b", fg="white").pack(fill=tk.X)

    # ---------- Scanning ----------
    def start_scan(self):
        if self.scanning:
            return
        self.scanning = True
        self.status.set("Scanning network...")
        threading.Thread(target=self.scan_thread, daemon=True).start()

    def stop_scan(self):
        self.scanning = False
        self.status.set("Stopped.")

    def scan_thread(self):
        prefix = self.prefix.get().strip()
        try:
            max_hosts = int(self.range_var.get())
        except Exception:
            max_hosts = DEFAULT_HOSTS
            self.range_var.set(DEFAULT_HOSTS)

        for i in range(1, max_hosts + 1):
            if not self.scanning:
                break
            ip = f"{prefix}.{i}"
            if ping(ip):
                macs = read_arp()
                mac = macs.get(ip, "")
                hostname = get_hostname(ip)
                vendor = vendor_from_mac(mac, self.oui_map)
                now = datetime.now().isoformat()
                if ip in self.devices:
                    self.devices[ip]["mac"] = mac
                    self.devices[ip]["hostname"] = hostname
                    self.devices[ip]["vendor"] = vendor
                    self.devices[ip]["last_seen"] = now
                else:
                    self.devices[ip] = {
                        "ip": ip,
                        "mac": mac,
                        "hostname": hostname,
                        "vendor": vendor,
                        "first_seen": now,
                        "last_seen": now
                    }
            self.status.set(f"Scanning {ip}")
        self.scanning = False
        self.status.set("Scan complete.")

    # ---------- Tree refresh ----------
    def refresh_tree_periodic(self):
        self.tree.delete(*self.tree.get_children())
        for ip, info in self.devices.items():
            self.tree.insert(
                "",
                tk.END,
                iid=ip,
                values=(
                    info.get("ip", ""),
                    info.get("mac", ""),
                    info.get("hostname", ""),
                    info.get("vendor", ""),
                    info.get("first_seen", ""),
                    info.get("last_seen", "")
                )
            )
        self.root.after(1000, self.refresh_tree_periodic)

    # ---------- Export ----------
    def export_json(self):
        path = filedialog.asksaveasfilename(defaultextension=".json")
        if not path:
            return
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.devices, f, indent=2)
        messagebox.showinfo("Saved", f"Data exported to {path}")

    # ---------- Script generation ----------
    def make_script_all(self):
        if not self.devices:
            messagebox.showinfo("No data", "No devices scanned yet.")
            return
        path = filedialog.asksaveasfilename(defaultextension=".sh", initialfile="openwrt_block_all.sh")
        if not path:
            return
        devices_list = list(self.devices.values())
        script = build_openwrt_block_script(devices_list)
        with open(path, "w", encoding="utf-8") as f:
            f.write(script)
        os.chmod(path, 0o755)
        self.last_script = path
        messagebox.showinfo("Saved", f"Script saved: {path}")

    def make_script_for_selected(self):
        sel = self.tree.selection()
        if not sel:
            messagebox.showinfo("Select", "Select one or more devices first.")
            return None
        selected_devices = []
        for iid in sel:
            info = self.devices.get(iid)
            if info:
                selected_devices.append(info)
        if not selected_devices:
            messagebox.showinfo("No data", "No valid devices selected.")
            return None
        # save temp script
        base = os.path.abspath(".")
        path = os.path.join(base, "openwrt_block_selected.sh")
        script = build_openwrt_block_script(selected_devices)
        with open(path, "w", encoding="utf-8") as f:
            f.write(script)
        os.chmod(path, 0o755)
        self.last_script = path
        return path

    # ---------- SSH / Disconnect ----------
    def deploy_last_script(self):
        if not self.last_script or not os.path.exists(self.last_script):
            messagebox.showerror("Error", "No script generated yet.")
            return
        self.deploy_script(self.last_script)

    def deploy_script(self, script_path):
        ip = self.router_ip.get().strip()
        user = self.router_user.get().strip()
        password = self.router_pass.get().strip()

        if not ip or not user or not password:
            messagebox.showerror("Error", "Fill router IP, user, and password.")
            return

        confirm = messagebox.askyesno(
            "Confirm",
            f"This will upload and execute:\n{os.path.basename(script_path)}\n"
            f"on router {user}@{ip}.\n\nMake sure you have a firewall backup.\nProceed?"
        )
        if not confirm:
            return

        try:
            self.status.set("Connecting to router via SSH...")
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(ip, username=user, password=password, timeout=10)

            sftp = ssh.open_sftp()
            remote_path = "/tmp/" + os.path.basename(script_path)
            sftp.put(script_path, remote_path)
            sftp.close()

            self.status.set("Executing script on router...")
            stdin, stdout, stderr = ssh.exec_command(f"chmod +x {remote_path} && {remote_path}")
            out = stdout.read().decode(errors="ignore")
            err = stderr.read().decode(errors="ignore")
            ssh.close()

            messagebox.showinfo(
                "Success",
                f"Script executed on router.\n\nOutput:\n{out or '(no output)'}\nErrors:\n{err or '(none)'}"
            )
            self.status.set("Deploy complete.")
        except Exception as e:
            messagebox.showerror("SSH Error", str(e))
            self.status.set("Failed.")

    def disconnect_selected(self):
        """
        Safe 'disconnect' = generate small firewall script for selected devices
        and deploy it immediately via SSH to your own OpenWrt router.
        """
        script_path = self.make_script_for_selected()
        if not script_path:
            return
        self.deploy_script(script_path)

# ========== MAIN ==========
if __name__ == "__main__":
    root = tk.Tk()
    app = NetworkGUI(root)
    root.mainloop()
